### ISSUE TITLE
Glob rules

### ISSUE THREAD

**Issue by S4n60w3n** [jpeddicord/askalono#57]
I am trying to match more license file names than default "glob". However i have issues with defining the rule. How to specify glob rule and what is the default? I need to add "License" and "Readme" file names

**Comment by S4n60w3n** [comment]
@jpeddicord Can you help me with that? There is too little documentation for that and I am kinda desperate

**Comment by jpeddicord** [comment]
The rules for the glob flag should match what's shown here: https://docs.rs/globset/0.4.5/globset/#syntax. If you're looking for something more advanced, you may want to consider using an external utility (like `find`) to list files, and then feed that into askalono:

`find -name 'LICENSE*' -exec askalono id '{}' \;` (see `man find` for info)

You can also use `askalono id --batch`, and askalono will wait for input filenames on stdin and print output in bulk. So if you have a list of filenames in a file, something like this should do the trick:

`cat my_files | askalono id --batch`

(the above commands may need tweaking; I'm not at my usual machine at the moment and can't test)

**Comment by S4n60w3n** [comment]
> The rules for the glob flag should match what's shown here: https://docs.rs/globset/0.4.5/globset/#syntax. If you're looking for something more advanced, you may want to consider using an external utility (like `find`) to list files, and then feed that into askalono:
> 
> `find -name 'LICENSE*' -exec askalono id '{}' \;` (see `man find` for info)
> 
> You can also use `askalono id --batch`, and askalono will wait for input filenames on stdin and print output in bulk. So if you have a list of filenames in a file, something like this should do the trick:
> 
> `cat my_files | askalono id --batch`
> 
> (the above commands may need tweaking; I'm not at my usual machine at the moment and can't test)

I have tries to use identify and put there file by file but it was way to slow, I`ll try to test the batch

**Comment by S4n60w3n** [comment]
@jpeddicord Thanks a lot for help, new glob rules works for me, i just had no idea what rust glob is
