### ISSUE TITLE
Default file name for crawl

### ISSUE THREAD

**Issue by dd-jy** [jpeddicord/askalono#65]
Hi!

I want to know the default file name lists for crawl.
When testing, it seems to be file names that includes LICENSE, COPYING, NOTICE.
I tried to find it in the source code, I couldn't see it.
Can you help me?

**Comment by jpeddicord** [comment]
The default names come from the `ignore` crate, which is a part of ripgrep:

https://github.com/BurntSushi/ripgrep/blob/master/crates/ignore/src/default_types.rs#L96-L122

To use a different pattern on the command line, you can pass `--glob` to change what matches.

**Comment by dd-jy** [comment]
Thanks for the quick reply!
It was very helpful to me. 😄
