### ISSUE TITLE
rmp-serde RUSTSEC vulnernability

### ISSUE THREAD

**Issue by RunBolt** [jpeddicord/askalono#99]
# Vulnerability

The crate `rmp-serde@0.14.4` has [RUSTSEC-2022-0092](https://rustsec.org/advisories/RUSTSEC-2022-0092). The target version in the current `Cargo.toml` (`0.14.0`) is yanked and thus the current set for `0.14.*` is `0.14.4`

# Recommended Changes
From the `RUSTSEC` it says to bump the version to `>=1.1.1`

**Comment by jpeddicord** [comment]
rmp-serde is now 1.1.1
